import Link from "next/link";
import Logo from "@/components/Logo";
import styles from "./page.module.css";

export const metadata = {
  title: "Terms of Use",
};

export default function TermsPage() {
  return (
    <div className={styles.wrap}>
      <Link className={styles.back} href="/">
        &larr; Back home
      </Link>
      <div style={{ marginBottom: 20 }}>
        <Logo href={null} markSize={26} />
      </div>
      <h1 className={styles.title}>Terms of Use</h1>
      <p className={styles.updated}>Last updated: August 4, 2026</p>

      <div className={styles.disclaimer}>
        This is a standard SaaS terms-of-use template, not legal advice. Placeholders like
        company name and governing law still need to be filled in, and a lawyer should review
        this — especially the liability and dispute sections — before you rely on it with real
        customers.
      </div>

      <div className={styles.content}>
        <h2>1. Acceptance of these terms</h2>
        <p>
          By creating an account or otherwise using CRM AI Agent (the &quot;Service&quot;), you
          agree to these Terms of Use. If you&apos;re agreeing on behalf of a company, you
          confirm you have the authority to bind that company to these terms.
        </p>

        <h2>2. What the Service does</h2>
        <p>
          The Service lets a company sign up, describe its business, and receive an
          AI-generated lead-capturing landing page and a configured CRM (contacts, pipeline,
          leads). Landing page copy and pipeline stages are generated using a third-party AI
          model (currently Google&apos;s Gemini) based on the information you provide, and can
          be edited after generation.
        </p>

        <h2>3. Accounts</h2>
        <p>
          You&apos;re responsible for the accuracy of the information you provide, for keeping
          your login credentials secure, and for all activity that happens under your account.
          Tell us promptly if you suspect unauthorized access to your account.
        </p>

        <h2>4. Acceptable use</h2>
        <p>You agree not to use the Service to:</p>
        <ul>
          <li>Collect, store, or send data you don&apos;t have the right to collect (e.g. leads gathered without consent where required by law);</li>
          <li>Send unsolicited communications (spam) to people captured through your landing page;</li>
          <li>Attempt to access another tenant&apos;s data, disrupt the Service, or circumvent its security;</li>
          <li>Use the Service for anything unlawful, fraudulent, or harmful to others.</li>
        </ul>

        <h2>5. Your data</h2>
        <p>
          You retain ownership of the leads, contacts, and other business data you or your
          customers submit through the Service (&quot;Customer Data&quot;). You&apos;re
          responsible for having the appropriate rights and consents to collect and process
          that data, including any personal data covered by privacy laws applicable to you
          (e.g. GDPR, CCPA). We process Customer Data only to provide the Service to you.
        </p>

        <h2>6. AI-generated content</h2>
        <p>
          Landing page copy, pipeline stages, and template selection may be generated by an AI
          model. AI-generated content can be inaccurate or unsuitable for your context — review
          and edit it before relying on it or publishing it to a public landing page. You are
          responsible for the content you ultimately publish, regardless of how it was
          generated.
        </p>

        <h2>7. Third-party services</h2>
        <p>
          The Service relies on third-party providers to operate, including a database
          provider (MongoDB Atlas), an AI provider (Google Gemini), and a transactional email
          provider (Resend) for account verification and password reset emails. Availability of
          the Service depends in part on these providers.
        </p>

        <h2>8. Fees</h2>
        <p>
          Some plans may be free and others paid, as described at signup or in your account
          settings. [Placeholder — fill in your actual pricing/billing terms once billing is
          live.]
        </p>

        <h2>9. Termination</h2>
        <p>
          You may stop using the Service and request deletion of your account at any time. We
          may suspend or terminate accounts that violate these terms or pose a security risk to
          the Service or other tenants.
        </p>

        <h2>10. Disclaimer of warranties</h2>
        <p>
          The Service is provided &quot;as is&quot; without warranties of any kind, express or
          implied, including warranties of merchantability, fitness for a particular purpose,
          or non-infringement. We don&apos;t guarantee the Service will be uninterrupted, secure,
          or error-free.
        </p>

        <h2>11. Limitation of liability</h2>
        <p>
          To the maximum extent permitted by law, [Company Name] will not be liable for any
          indirect, incidental, special, consequential, or punitive damages, or any loss of
          profits or data, arising from your use of the Service. [Placeholder — a lawyer should
          tailor this section, including any liability cap, to your jurisdiction and business.]
        </p>

        <h2>12. Governing law</h2>
        <p>
          These terms are governed by the laws of [Jurisdiction — placeholder]. Any disputes
          will be resolved in the courts of that jurisdiction, unless otherwise required by
          applicable law.
        </p>

        <h2>13. Changes to these terms</h2>
        <p>
          We may update these terms from time to time. If we make material changes, we&apos;ll
          make reasonable efforts to notify account owners (e.g. by email or an in-app notice)
          before the changes take effect.
        </p>

        <h2>14. Contact</h2>
        <p>
          Questions about these terms? Contact us at [support email — placeholder].
        </p>
      </div>
    </div>
  );
}
